---
- name: Instash zsh
  become: true
  community.general.pacman:
    package:
      - wget
      - zsh
    update_cache: true

- name: Install Oh My Zsh
  ansible.builtin.command:
    cmd: sh -c "$(wget -O- https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --unattended
  creates: "{{ ansible_facts.user_dir }}/.oh-my-zsh"